baseurl = "https://example.org/"
languageCode = "en-us"
title = "Robert's Website"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Robert Swartz"
	description = "Accountant"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Robert Swartz Accounting"

		[params.navigation.links]
			about     = "About"
			#services  = "Services"
			contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		image      = "true"
		slogan     = "Robert Swartz"
		subtitle   = "Accountant"
		subtitle2  = "Created by Tyler Swartz"

	# About section
	[params.about]
		headline    = "I am Robert Swartz"
		description = "A freelance accountant who graduated from Rutgers University with a degree in Accounting.  Graduate of Rutgers Law School as well."
		subtitle = "Created by Tyler Swartz"

	# Service section
	[params.services]
		headline = "Frequently Asked Questions"

        [[params.services.list]]
						title = "lets go!"
            description = "Our templates are updated regularly so they don't break."

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
		#headline = "Get the Creative Theme for Hugo"

		#[params.aside.button]
		#	text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"
#
	# Contact section
	[params.contact]
		headline = "Want to contact me?"
		description = "You can find my contact information below:"
		phone = "856-506-1671"
		email = "rswartz96@comcast.net"
		twitter = "http://twitter.com/realDralian"

		#Google Maps section
		[params.location]
			latitude  = "39.879185"
		 longitude = "-74.931106"
